<?php

namespace Elastic\Apm\PhpAgent\Model;


use Elastic\Apm\PhpAgent\Model\Virtualize\Kubernetes;
use Elastic\Apm\PhpAgent\Util\BaseObject;

class System extends BaseObject
{
    /**
     * Architecture of the system the agent is running on.
     *
     * @var string
     */
    protected $architecture;

    /**
     * Hostname of the system the agent is running on.
     *
     * @var string
     */
    protected $hostname;

    /**
     * Name of the system platform the agent is running on.
     *
     * @var string
     */
    protected $platform;

    /**
     * @var Kubernetes
     */
    protected $kubernetes;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $systemInfo  = \posix_uname();
        if (null === $this->architecture) {
            $this->architecture = $systemInfo['machine'];
        }
        if (null === $this->platform) {
            $this->platform = $systemInfo['sysname'];
        }
        if (null === $this->hostname) {
            $this->hostname = \gethostname();
        }
    }

    /**
     * @param string $architecture
     */
    public function setArchitecture(string $architecture)
    {
        $this->architecture = $architecture;
    }

    /**
     * @param string $hostname
     */
    public function setHostname(string $hostname)
    {
        $this->hostname = $hostname;
    }

    /**
     * @param string $platform
     */
    public function setPlatform(string $platform)
    {
        $this->platform = $platform;
    }

    /**
     * @param Kubernetes $kubernetes
     */
    public function setKubernetes(Kubernetes $kubernetes)
    {
        $this->kubernetes = $kubernetes;
    }



    /**
     * @return array
     */
    public function toArray(): array
    {
        return [
            'architecture' => $this->architecture,
            'hostname' => $this->hostname,
            'platform' => $this->platform,
            'kubernetes' => $this->kubernetes
        ];
    }

    /**
     * Define object validation rules
     *
     * @return array
     */
    public function validationRules(): array
    {
        return [
            'maxLength' => [
                'architecture' => 1024,
                'hostname' => 1024,
                'platform' => 1024
            ]
        ];
    }
}